Repository github/evergreen, pull requests merged in 2024-01, with the labels that each got.

#20 Configure test coverage files and add tests
  .coveragerc
  Makefile
  evergreen.py
  test_dependabot_file.py
  test_evergreen.py
Labels: enhancement

#21 Handle pull request write failures
  evergreen.py
Labels: bug

#30 Fix DRY_RUN always being true
  env.py
  test_env.py
Labels: bug

#31 Configurable commit message
  README.md
  env.py
  evergreen.py
  test_env.py
  test_evergreen.py
Labels: enhancement

#38 Measure this repo when logging contributors
  .github/workflows/contributors_report.yaml
Labels: infrastructure

#36 feat: add-project-support
  README.md
  env.py
  evergreen.py
  test_env.py
  test_evergreen.py
Labels: enhancement
