Repository github/evergreen, pull requests merged in 2024-04, with the labels that each got.

#79 feat: github app authentication and repo standardization
  .github/linters/.flake8
  .github/linters/.markdown-lint.yml
  .github/linters/.mypy.ini
  .github/linters/.python-lint
  .github/workflows/contributors_report.yaml
  .github/workflows/docker-ci.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/python-ci.yml
  .github/workflows/release-drafter.yml
  .github/workflows/stale.yaml
  .github/workflows/super-linter.yaml
  .pylintrc
  Dockerfile
  Makefile
  README.md
  auth.py
  env.py
  evergreen.py
  requirements-test.txt
  requirements.txt
  test_auth.py
  test_env.py
  test_evergreen.py
Labels: documentation, enhancement, dependencies

#83 fix: remove time of day and tz info properly
  evergreen.py
  test_evergreen.py
Labels: bug

#91 docs: add github issue templates
  .env-example
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/dependabot.yml
  README.md
Labels: documentation

#93 fix: ensure created_after_date is formatted string before date comparison
  README.md
  env.py
  test_env.py
  test_evergreen.py
Labels: bug

#97 docs: add note about `administration:write` permission for security updates
  README.md
Labels: documentation

#96 fix: referring to mix package key as hex.
  dependabot_file.py
  test_dependabot_file.py
Labels: bug

#99 feat: automated releases and auto labelling
  .github/pull_request_template.md
  .github/release-drafter.yml
  .github/workflows/auto-labeler.yml
  .github/workflows/pr-title.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
Labels: enhancement

#101 chore: add skip debug prints
  evergreen.py
Labels: maintenance

#106 chore(deps): update dependabot config to include pr prefixes
  .github/dependabot.yml
  env.py
  requirements-test.txt
  test_env.py
Labels: maintenance

#110 chore: Update pull_request_template.md
  .github/pull_request_template.md
Labels: maintenance

#103 fix: use GitHub App token when authed with GitHub App
  .env-example
  auth.py
  env.py
  evergreen.py
  test_auth.py
  test_env.py
Labels: fix

#109 fix: Skip date testing if not configured
  evergreen.py
Labels: fix

#116 fix: yaml hierarchy indicates 2 spaces instead of 4
  dependabot_file.py
  test_dependabot_file.py
Labels: fix

#119 feat: release on specific labels
  .github/release-drafter.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
Labels: feature
