Repository github/evergreen, pull requests merged in 2024-05, with the labels that each got.

#122 chore: add OSSF scorecard github action and README badge
  .github/workflows/auto-labeler.yml
  .github/workflows/contributors_report.yaml
  .github/workflows/docker-ci.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-ci.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/stale.yaml
  .github/workflows/super-linter.yaml
  README.md
Labels: maintenance

#128 chore: group dependabot dependency updates for minor/patch updates
  .github/dependabot.yml
  .github/workflows/contributors_report.yaml
  .github/workflows/docker-ci.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-ci.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/super-linter.yaml
Labels: maintenance, release

#132 chore: Switch to weekly dep updates to reduce noise
  .github/dependabot.yml
Labels: maintenance

#137 chore: add pull_request_target for releases
  .github/workflows/release.yml
Labels: maintenance

#139 fix: typo in env-example
  .env-example
Labels: fix

#140 feat: Update existing configs with missing package-ecosystems
  .env-example
  .github/linters/.python-lint
  README.md
  dependabot_file.py
  env.py
  evergreen.py
  requirements-test.txt
  requirements.txt
  test_dependabot_file.py
  test_env.py
Labels: feature

#144 test: Expand test coverage to 100% on `evergreen.py`
  evergreen.py
  test_dependabot_file.py
  test_evergreen.py
Labels: automation

#143 refactor: loop logic for iterating over package-ecosystems
  README.md
  dependabot_file.py
Labels: automation

#148 chore: remove pull_request target if we already have pull_request_target
  .github/workflows/auto-labeler.yml
  .github/workflows/release.yml
Labels: maintenance

#149 ci: Add Jeff to review new data releases
  .github/pull_request_template.md
Labels: automation

#150 fix: maintain dependabot config filename for existing configs
  README.md
  dependabot_file.py
  env.py
  evergreen.py
  test_dependabot_file.py
  test_env.py
  test_evergreen.py
Labels: fix, release

#155 ci: Add test for Terraform dependabot config
  test_dependabot_file.py
Labels: automation
