Repository github/evergreen, pull requests merged in 2024-11, with the labels that each got.

#264 chore: improve auth test coverage
  test_auth.py
Labels: maintenance

#265 feat: support private repository configuration
  .env-example
  .gitignore
  README.md
  dependabot_file.py
  env.py
  evergreen.py
  requirements.txt
  test_dependabot_file.py
  test_env.py
  test_evergreen.py
Labels: release, feature

#273 fix: continue on no update for repository
  evergreen.py
Labels: fix, release
