Repository github/evergreen, pull requests merged in 2024-03, with the labels that each got.

#66 The ignore directive of jscpd is not working as expected
  .github/linters/.jscpd.json
Labels: bug

#60 Filter repositories in scope by their visibility
  README.md
  env.py
  evergreen.py
  test_env.py
Labels: enhancement

#71 Create stale.yaml
  .github/workflows/stale.yaml
Labels: infrastructure

#69 Ignore package ecosystems
  README.md
  dependabot_file.py
  env.py
  evergreen.py
  test_dependabot_file.py
  test_env.py
Labels: enhancement

#73 Batching
  README.md
  env.py
  evergreen.py
  test_env.py
Labels: enhancement
