Repository github/evergreen, pull requests merged in 2024-10, with the labels that each got.

#240 chore: use setup python to pin the pip version
  .github/workflows/python-ci.yml
  .github/workflows/super-linter.yaml
Labels: maintenance

#238 feat: Add configuration option for dependabot labels
  README.md
  dependabot_file.py
  env.py
  evergreen.py
  test_dependabot_file.py
  test_env.py
Labels: feature

#243 docs: add ossf badge with link to project details
  README.md
Labels: documentation

#242 feat: filter repos by team ownership
  README.md
  env.py
  evergreen.py
  test_env.py
  test_evergreen.py
Labels: release, feature

#239 feat: Add maven package ecosystem detection
  README.md
  dependabot_file.py
  test_dependabot_file.py
Labels: feature

#256 feat: support github enterprise api
  .env-example
  .github/linters/.markdown-lint.yml
  README.md
  auth.py
  env.py
  evergreen.py
  test_auth.py
  test_env.py
  test_evergreen.py
Labels: release, feature

#258 fix: update README on missing permissions for app
  README.md
Labels: fix
