Repository github/evergreen, pull requests merged in 2024-06, with the labels that each got.

#157 ci: Add test for GitHub Actions dependabot configuration
  test_dependabot_file.py
Labels: automation

#158 feat: Repo specific exemptions
  .env-example
  README.md
  dependabot_file.py
  env.py
  evergreen.py
  test_dependabot_file.py
  test_env.py
Labels: feature

#164 chore: add Jacob to pr reviews automatically
  .github/CODEOWNERS
Labels: maintenance

#165 chore: standardize github action types
  .github/workflows/auto-labeler.yml
  .github/workflows/docker-ci.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-ci.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/super-linter.yaml
  env.py
  test_env_get_bool.py
Labels: maintenance

#169 chore: pin shas in Dockerfile
  Dockerfile
Labels: maintenance
