Repository github/evergreen, pull requests merged in 2025-01, with the labels that each got.

#297 feat: move to reusable workflows
  .github/release-drafter.yml
  .github/workflows/auto-labeler.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/release.yml
Labels: feature

#288 fix: summary project output
  evergreen.py
Labels: fix, release

#306 chore: update ospo-reusable-workflows and semver
  .github/release-drafter.yml
  .github/workflows/auto-labeler.yml
  .github/workflows/pr-title.yml
  .github/workflows/release.yml
Labels: maintenance, release
